# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]

platform :ios do
    ios_dir = File.expand_path('../ios')

    desc "Get certificates"
    lane :sync_certs do
        sync_code_signing(
            git_branch: "main",
            type: "development",
            app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
            force_for_new_devices: true,
            readonly: true
        )

        # You can repeat the sync_code_signing with other types of certificates such as appstore and adhoc
        sync_code_signing(
            git_branch: "main",
            type: "appstore",
            app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
            readonly: true
        )
    end

    desc "Generate new development certificates"
    lane :generate_new_certs_dev do
      sync_code_signing(
        git_branch: "main",
        type: "development",
        app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
        force_for_new_devices: true,
        readonly: false
      )
    end

    desc "Generate new appstore certificates"
    lane :generate_new_certs_appstore do
      sync_code_signing(
        git_branch: "main",
        type: "appstore",
        app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
        force_for_new_devices: true,
        readonly: false
      )
    end

    lane :build_beta do
        setup_ci if ENV['CI']
        sync_certs
        build_app(
            configuration: "Release",
            workspace: File.join(ios_dir, "App/App.xcworkspace"),
            scheme: "App", 
            export_method: "app-store",
            export_options: {
              provisioningProfiles: {
                  DEVELOPER_APP_ID => "#{PROVISIONING_PROFILE_SPECIFIER}"
              }
            },
            clean: true,
            )
      end

    lane :upload_beta do
        build_beta
        upload_to_testflight(
            beta_app_feedback_email: "salemlfenn@gmail.com",
        )
    end
end

platform :android do
    android_dir = File.expand_path('../android')

    lane :buildApk do
        gradle(task: 'clean', project_dir: android_dir)
        gradle(
            task: "assemble", 
            project_dir: android_dir,   
        )
        APK_LOCATION = "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
        sh("cp", "#{APK_LOCATION}", ENV["OUTPUT_PATH"])
    end

    lane :buildBundle do
        gradle(task: 'clean', project_dir: android_dir)
        gradle(
            task: "bundleRelease", 
            project_dir: android_dir,
            properties: {
                "android.injected.signing.store.file" => File.join(Dir.pwd, "..", ENV["KEYSTORE_FILE_PATH"]),
                "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
                "android.injected.signing.key.alias" => ENV["KEYSTORE_ALIAS"],
                "android.injected.signing.key.password" => ENV["KEYSTORE_PASSWORD"],
            }
        )

        AAB_LOCATION = "#{lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"
        sh("cp", "#{AAB_LOCATION}", ENV["OUTPUT_PATH"])
    end
end