name: Build Dev Version of App
on:
  workflow_dispatch:
env:
  VITE_SENTRY_DSN: ${{ vars.VITE_SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Create build
        run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - name: Sync with capacitor
        run: npx cap sync
      - name: Set up Ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      - name: Build Android APK
        run: bundle exec fastlane android buildApk
        env:
          OUTPUT_PATH: hakubun.apk
      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hakubun-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
